services:
  payment-service:
    build:
      context: .
    image: ${PAYMENT_NAME}:latest
    container_name: ${PAYMENT_NAME}
    ports:
      - ${PAYMENT_PORT}:${PAYMENT_PORT}
    environment:
      - PAYMENT_NAME=${PAYMENT_NAME}
      - PAYMENT_PORT=${PAYMENT_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TOSS_SECRET_KEY=${TOSS_SECRET_KEY}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${PAYMENT_PORT}/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - spring_logs:/logs
    networks:
      - ${NETWORK}

networks:
  berry-network:
    external: true

volumes:
  spring_logs: