services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@${KAFKA_INTERNAL_HOST}:${KRAFT_CONTROLLER_PORT}
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # Listeners
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CONTROLLER://${KAFKA_INTERNAL_HOST}:${KRAFT_CONTROLLER_PORT},INTERNAL://${KAFKA_INTERNAL_HOST}:${KAFKA_INTERNAL_PORT},EXTERNAL://0.0.0.0:${KAFKA_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://${KAFKA_INTERNAL_HOST}:${KAFKA_INTERNAL_PORT},EXTERNAL://${KAFKA_HOST}:${KAFKA_PORT}
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - ${KAFKA_PORT}:${KAFKA_INTERNAL_PORT}
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost ${KAFKA_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ${NETWORK}

  redis:
    image: redis:7.0
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - ${NETWORK}

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_PORT}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - ${NETWORK}

networks:
  berry-network:
    external: true

volumes:
  kafka_data:
  mysql_data:
  redis_data: