services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:${KAFKA_PORT}
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "echo dump | nc zookeeper 2181 | grep brokers"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - common-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
    healthcheck:
      test: ["CMD", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - common-network

  common-redis:
    image: redis:7.0
    container_name: common-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - ${COMMON_REDIS_PORT}:${COMMON_REDIS_PORT}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - common-network

networks:
  common-network:
    external: true

volumes:
  redis_data:
