services:
  gateway-service:
    build:
      context: .
    image: ${GATEWAY_NAME}:latest
    container_name: ${GATEWAY_NAME}
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      - GATEWAY_NAME=${GATEWAY_NAME}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - USER_NAME=${USER_NAME}
      - POST_NAME=${POST_NAME}
      - BID_NAME=${BID_NAME}
      - BID_PORT={BID_PORT}
      - DELIVERY_NAME=${DELIVERY_NAME}
      - PAYMENT_NAME=${PAYMENT_NAME}
      - AUTH_NAME=${AUTH_NAME}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - TZ=${TZ}
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${GATEWAY_PORT}/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - ${NETWORK}

networks:
  berry-network:
    external: true