services:
  eureka-server:
    build:
      context: .
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - ${EUREKA_PORT}:${EUREKA_PORT}
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - TZ=${TZ}
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${EUREKA_PORT}/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - ${NETWORK}

networks:
  berry-network:
    external: true