services:
  auth-service:
    build:
      context: .
    image: ${AUTH_NAME}:latest
    container_name: ${AUTH_NAME}
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    environment:
      - AUTH_NAME=${AUTH_NAME}
      - AUTH_PORT=${AUTH_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_SECRET=${JWT_SECRET}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${AUTH_PORT}/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - spring_logs:/logs
    networks:
      - ${NETWORK}

networks:
  berry-network:
    external: true

volumes:
  spring_logs: