spring:
  application:
    name: ${GATEWAY_NAME}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: JwtFilter
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: ${AUTH_NAME}
          uri: lb://${AUTH_NAME}
          predicates:
            - Path=/api/v1/auth/**
        - id: ${AUTH_NAME}-admin
          uri: lb://${AUTH_NAME}
          predicates:
            - Path=/admin/v1/auth/**

        - id: ${USER_NAME}
          uri: lb://${USER_NAME}
          predicates:
            - Path=/api/v1/users/**
        - id: ${USER_NAME}-admin
          uri: lb://${USER_NAME}
          predicates:
            - Path=/admin/v1/users/**

        - id: report-service
          uri: lb://${USER_NAME}
          predicates:
            - Path=/api/v1/reports/**
        - id: report-service-admin
          uri: lb://${USER_NAME}
          predicates:
            - Path=/admin/v1/reports/**

        - id: post-service
          uri: lb://${POST_NAME}
          predicates:
            - Path=/api/v1/posts/**
        - id: post-service-admin
          uri: lb://${POST_NAME}
          predicates:
            - Path=/admin/v1/posts/**

        - id: category-service
          uri: lb://${POST_NAME}
          predicates:
            - Path=/api/v1/categories/**
        - id: category-service-admin
          uri: lb://${POST_NAME}
          predicates:
            - Path=/admin/v1/categories/**

        - id: review-service
          uri: lb://${POST_NAME}
          predicates:
            - Path=/api/v1/reviews/**
        - id: review-service-admin
          uri: lb://${POST_NAME}
          predicates:
            - Path=/admin/v1/reviews/**

        - id: like-service
          uri: lb://${POST_NAME}
          predicates:
            - Path=/api/v1/likes/**
        - id: like-service-admin
          uri: lb://${POST_NAME}
          predicates:
            - Path=/admin/v1/likes/**

        - id: ${DELIVERY_NAME}
          uri: lb://${DELIVERY_NAME}
          predicates:
            - Path=/api/v1/deliveries/**
        - id: ${DELIVERY_NAME}-admin
          uri: lb://${DELIVERY_NAME}
          predicates:
            - Path=/admin/v1/deliveries/**

        - id: notification-service
          uri: lb://${DELIVERY_NAME}
          predicates:
            - Path=/api/v1/notifications/**
        - id: notification-service-admin
          uri: lb://${DELIVERY_NAME}
          predicates:
            - Path=/admin/v1/notifications/**

        - id: ${BID_NAME}
          uri: lb://${BID_NAME}
          predicates:
            - Path=/api/v1/bids/**
        - id: ${BID_NAME}-admin
          uri: lb://${BID_NAME}
          predicates:
            - Path=/admin/v1/bids/**
        - id: bid-service-websocket
          uri: lb://${BID_NAME}
          predicates:
            - Path=/ws/**
          filters:
            - PreserveHostHeader

        - id: ${PAYMENT_NAME}
          uri: lb://${PAYMENT_NAME}
          predicates:
            - Path=/api/v1/payments/**
        - id: ${PAYMENT_NAME}-admin
          uri: lb://${PAYMENT_NAME}
          predicates:
            - Path=/admin/v1/payments/**

server:
  port: ${GATEWAY_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGINS}