global:
  scrape_interval: 15s  # 기본 스크래핑 간격

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'eureka-server:8761'
          - 'gateway-service:8080'
          - 'user-service:8081'
          - 'post-service:8082'
          - 'bid-service:8083'
          - 'delivery-service:8084'
          - 'payment-service:8085'
          - 'auth-service:8086'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']