global:
  scrape_interval: 15s  # 기본 스크래핑 간격

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '${EUREKA_NAME}:${EUREKA_PORT}'
          - '${GATEWAY_NAME}:${GATEWAY_PORT}'
          - '${USER_NAME}:${USER_PORT}'
          - '${POST_NAME}:${POST_PORT}'
          - '${BID_NAME}:${BID_PORT}'
          - '${DELIVERY_NAME}:${DELIVERY_PORT}'
          - '${PAYMENT_NAME}:${PAYMENT_PORT}'
          - '${AUTH_NAME}:${AUTH_PORT}'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:${PROMETHEUS_PORT}']