spring:
  application:
    name: eureka

server:
  port: ${EUREKA_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    # 유레카 서버와 통신하기 위한 기본 서비스 URL
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

  instance:
    hostname: ${EUREKA_HOST}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST}:${ZIPKIN_PORT}"
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi