spring:
  application:
    name: eureka

server:
  port: ${PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    # 유레카 서버와 통신하기 위한 기본 서비스 URL
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}