services:
  post-service:
    build:
      context: .
    image: ${POST_NAME}:latest
    container_name: ${POST_NAME}
    ports:
      - ${POST_PORT}:${POST_PORT}
    environment:
      - POST_NAME=${POST_NAME}
      - POST_PORT=${POST_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TZ=${TZ}
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${POST_PORT}/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - spring_logs:/logs
    networks:
      - ${NETWORK}

networks:
  berry-network:
    external: true

volumes:
  spring_logs: