spring:
  application:
    name: ${AUTH_NAME}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: ${AUTH_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST}:${ZIPKIN_PORT}"
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi

logging:
  level:
    org.springframework.security: DEBUG