server:
  port: 8086

spring:
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/