server:
  port: ${PORT}

spring:
  application:
    name: auth-service
  data:
    redis:
      host: ${AUTH_REDIS_HOST}
      port: ${AUTH_REDIS_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  level:
    org.springframework.security: DEBUG