services:
  bid-service:
    build:
      context: .
    image: bid-service:latest
    container_name: bid-service
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BID_REDIS_HOST=${BID_REDIS_HOST}
      - BID_REDIS_PORT=${BID_REDIS_PORT}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_DEFAULT_ZONE=${EUREKA_DEFAULT_ZONE}
    env_file:
      - ../.env
      - .env
    depends_on:
      bid-mysql:
        condition: service_healthy
      bid-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - spring_logs:/logs
    networks:
      - msa-network
      - common-network

  bid-mysql:
    image: mysql:8.0
    container_name: bid-mysql
    environment:
      MYSQL_DATABASE: bid
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - msa-network

  bid-redis:
    image: redis:7.0
    container_name: bid-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - msa-network

networks:
  msa-network:
    external: true
  common-network:
    external: true

volumes:
  mysql_data:
  redis_data:
  spring_logs: