services:
  delivery-service:
    build:
      context: .
    image: ${DELIVERY_NAME}:latest
    container_name: ${DELIVERY_NAME}
    ports:
      - ${DELIVERY_PORT}:${DELIVERY_PORT}
    environment:
      - DELIVERY_NAME=${DELIVERY_NAME}
      - DELIVERY_PORT=${DELIVERY_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${DELIVERY_PORT}/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - spring_logs:/logs
    networks:
      - ${NETWORK}

networks:
  berry-network:
    external: true

volumes:
  spring_logs: