version: '3.4'

services:
  mysql:
    image: mysql:8.0
    container_name: delivery_mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivery_spring
    ports:
      - "${SPRING_PORT}:8080"
    environment:
      SPRING_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:mysql://delivery_mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      EUREKA_SERVER: ${EUREKA_SERVER}
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - spring_logs:/logs

volumes:
  mysql_data:
  redis_data:
  spring_logs:
