services:
  user-service:
    build:
      context: .
    image: ${USER_NAME}:latest
    container_name: ${USER_NAME}
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      - USER_NAME=${USER_NAME}
      - USER_PORT=${USER_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - TZ=${TZ}
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${USER_PORT}/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - spring_logs:/logs
    networks:
      - ${NETWORK}

networks:
  berry-network:
    external: true

volumes:
  spring_logs: